# Generated by Django 4.2.4 on 2023-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookShelf', '0003_remove_booklist_id_booklist_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklist',
            name='book_id',
        ),
        migrations.AddField(
            model_name='booklist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
